# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  sln: '$(Build.Repository.LocalPath)\src\Microsoft.DotnetOrg.Policies.sln'
  outDir: '$(Build.ArtifactStagingDirectory)\'
  policop: '$(Build.ArtifactStagingDirectory)\policop.exe'
  cachePath: '$(Build.ArtifactStagingDirectory)'
  violationsPath: '$(Build.ArtifactStagingDirectory)\dotnet.csv'

jobs:
- job:
  timeoutInMinutes: 120
  steps:
  - task: NuGetToolInstaller@1
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(sln)'
  - task: MSBuild@1
    inputs:
      solution: '$(sln)'
      msbuildArguments: '/p:OutDir=$(outDir)'
  - task: CmdLine@2
    inputs:
      script: |
        $(policop) cache-org --org dotnet --with-ms-links --github-token $(GitHubToken) --ospo-token $(TokenOspo)
        $(policop) cache-export -o $(cachePath)
        $(policop) check --org dotnet -o $(violationsPath) --policy-repo terrajobst/org-policy-violations --github-token $(GitHubToken)
        $(policop) cache-clear -f
    condition: and(succeeded(), not(eq(variables['GitHubToken'], '')), not(eq(variables['OspoToken'], '')), or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual')))
  - task: PublishBuildArtifacts@1
    condition: eq(variables['system.pullrequest.isfork'], false)
